name: AutoPickup
version: 1.0.0
main: com.autopickup.AutoPickupPlugin
api-version: '1.21'
authors: [Jonas1903]
description: Auto pickup and auto smelt items directly into inventory

commands:
  autopickup:
    description: Toggle auto pickup settings
    usage: /<command> [admin|give|reload]
    aliases: [ap]

permissions:
  autopickup.use:
    description: Allows using auto pickup features
    default: true
  autopickup.admin:
    description: Access admin configuration
    default: op
  autopickup.converter:
    description: Use ore converter item
    default: true
  autopickup.autoconvert:
    description: Enable automatic periodic inventory conversion
    default: true
